
# Obtain an OAuth access token from https://developers.docusign.com/oauth-token-generator
access_token= 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjY4MTg1ZmYxLTRlNTEtNGNlOS1hZjFjLTY4OTgxMjIwMzMxNyJ9.eyJUb2tlblR5cGUiOjUsIklzc3VlSW5zdGFudCI6MTU5ODg4OTY3NiwiZXhwIjoxNTk4OTE4NDc2LCJVc2VySWQiOiI3NmExNDM0Yy03YjFjLTQzYTAtODljZi1iODE3MDczNTQwOTciLCJzaXRlaWQiOjEsInNjcCI6WyJzaWduYXR1cmUiLCJjbGljay5tYW5hZ2UiLCJvcmdhbml6YXRpb25fcmVhZCIsInJvb21fZm9ybXMiLCJncm91cF9yZWFkIiwicGVybWlzc2lvbl9yZWFkIiwidXNlcl9yZWFkIiwidXNlcl93cml0ZSIsImFjY291bnRfcmVhZCIsImRvbWFpbl9yZWFkIiwiaWRlbnRpdHlfcHJvdmlkZXJfcmVhZCIsImR0ci5yb29tcy5yZWFkIiwiZHRyLnJvb21zLndyaXRlIiwiZHRyLmRvY3VtZW50cy5yZWFkIiwiZHRyLmRvY3VtZW50cy53cml0ZSIsImR0ci5wcm9maWxlLnJlYWQiLCJkdHIucHJvZmlsZS53cml0ZSIsImR0ci5jb21wYW55LnJlYWQiLCJkdHIuY29tcGFueS53cml0ZSJdLCJhdWQiOiJmMGYyN2YwZS04NTdkLTRhNzEtYTRkYS0zMmNlY2FlM2E5NzgiLCJhenAiOiJmMGYyN2YwZS04NTdkLTRhNzEtYTRkYS0zMmNlY2FlM2E5NzgiLCJpc3MiOiJodHRwczovL2FjY291bnQtZC5kb2N1c2lnbi5jb20vIiwic3ViIjoiNzZhMTQzNGMtN2IxYy00M2EwLTg5Y2YtYjgxNzA3MzU0MDk3IiwiYW1yIjpbImludGVyYWN0aXZlIl0sImF1dGhfdGltZSI6MTU5ODg4OTY2OCwicHdpZCI6IjU0YTkwZWFiLWEzNTItNDZiYy1hMDRlLTM0Nzc2MjMzMTIzOSJ9.AiS8w_S-l1oDKp65T2L0lcYd0ZXqvARhxyDB5vpkys77_7v5UA88vvPo5t3LISzblqRe69sNQGR79rECzqlkR84kX3Ag6jX78Bxdqy0GibWBABu6WKZTXImBZu1tI_Wow2TQgKXq_WUW1qWYDLcDAr_c5oevR6PrsPZprkiUowwPADJ0QqMtjByhTroFXT2lTbF7sfvR85tSNBSvKZxNO5Irap_n_h_X82mRgjGCwboGBd3khRzVuc37jDDeUvv5_VCymhxxPkY--KnFwnDL3EvziUDj52mvISHL5XQE9NoIUiiAp8Rjz67aqZyL-4EV9C2HtnnaGlQuHEm4rtjZhg'
# Obtain your accountId from demo.docusign.com -- the account id is shown in the drop down on the upper right corner of the screen by your picture or the default picture.
account_id= '11321217'
# Recipient Information:
signer_name= 'tbd:Loyal Customer'
signer_email= 'tbd:l.o.y.a.l.t.y.amaan@gmail.com'
# The url of this web application
base_url= 'http://127.0.0.1:5000'
# Used to indicate that the signer will use an embedded Signing Ceremony. Represents the signer's userId within your application.
client_user_id= '123'
# How is this application authenticating the signer? See the `authenticationMethod' definition https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeViews/createRecipient
authentication_method= 'None'
# The API base_path
base_path= 'https://demo.docusign.net/restapi'